"""add_title_to_steps

Revision ID: 37a53ae526b0
Revises: 60e0bdd38951
Create Date: 2026-01-29 12:43:44.634440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a53ae526b0'
down_revision: Union[str, None] = '60e0bdd38951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'title')
    # ### end Alembic commands ###
