"""init_steps_architecture

Revision ID: 60e0bdd38951
Revises: 641a6d932138
Create Date: 2026-01-29 10:59:41.680804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60e0bdd38951'
down_revision: Union[str, None] = '641a6d932138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('quiz_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'order_number', name='uq_lesson_step_order')
    )
    op.add_column('lessons', sa.Column('is_free', sa.Boolean(), nullable=False))
    op.drop_column('lessons', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('lessons', 'is_free')
    op.drop_table('steps')
    # ### end Alembic commands ###
