"""update_purchase_table_add_status

Revision ID: 641a6d932138
Revises: 5cb538c70323
Create Date: 2026-01-27 09:50:37.158299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql
# revision identifiers, used by Alembic.
revision: str = '641a6d932138'
down_revision: Union[str, None] = '5cb538c70323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    purchase_status = postgresql.ENUM('PENDING', 'SUCCEEDED', 'CANCELED', name='purchasestatus')
    purchase_status.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('payment_id', sa.String(length=255), nullable=True))
    op.add_column('purchases', sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'CANCELED', name='purchasestatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'status')
    op.drop_column('purchases', 'payment_id')
    # ### end Alembic commands ###
    purchase_status = postgresql.ENUM('PENDING', 'SUCCEEDED', 'CANCELED', name='purchasestatus')
    purchase_status.drop(op.get_bind())