"""add is_edited to CommentORM

Revision ID: ac1c43bf1047
Revises: 4769ce55d5d5
Create Date: 2026-02-12 12:35:18.498559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac1c43bf1047'
down_revision: Union[str, None] = '4769ce55d5d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_edited', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'is_edited')
    # ### end Alembic commands ###
